---
title: "Chapter 1 Notes"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## 1.1 What Can Be Forecast

The predictability of an event or quantity depends on:

  1. how well we understand the factors that contribute to it
  2. how much data is available
  3. how similar the future is to the past
  4. whether the forecasts themselves can affect the thing we are tyring to forecast

A key step is knowing when something can be forecast accurately and when a forecast
will be no better than a coin flip.
Every environment is changing and a good forecasting model can capture the way 
in which it is changing.

There are many models to use for forecasting varying from simple to complex. The 
choice of method will depend on available data and the predictability of the 
object to be forecast.

***


## 1.4 Forecasting Data and Methods

* Qualitative Forecasting - for when data is not available 
* Quantitative Forecasting - for when data is available. Requires:
  + numerical information about the past
  + an assumption that some aspects of past patterns will occur in the future
  
***


## 1.6 Basic Steps in a Forecasting Task

1. Problem definition
2. Gathering information / data
3. Exploratory analysis
4. Choosing and fitting models
5. Using and evaluating a model

***


## 1.7 The Statistical Forecasting Perspective

Anything we try to forecast is a random variable; it is unknown in its essence. 
There are many possible futures to be imagined. A forecast is estimating the 
_middle_ of the range of possible values of the variable. Forecasts are usually
accompanied by a **prediction interval** giving a _range_ of values the random
variable could be with relatively high probability.This middle range or average
is called the **point forecast**.



#### Short hand meanings

$y_t$: an observation, $y$, at time $_t$

Supposed all observed information is represented as: $\mathcal{I}$. 

$y_t|\mathcal{I}$ would mean "the random variable $y_t$ given what we know in $\mathcal{I}$

The set of values and relative probabilities of this random variable is the 
**probability distribution**. When forecasting, it is the **forecast distribution**.

$\hat{y}_t$: Termed "y hat", and is the point forecast of $y_t$



#### Examples of Short hand

$\hat{y}_{t|t-1}$: this would mean the forecast of $y_t$ taking account of all 
previous observations

$\hat{y}_{T+h|T}$: the forecast of $y_{T+h}$ taking account of all observations
up to time $T$ via steps of $h$ size

***

